name: vlogproject
channels:
  - defaults
dependencies:
  - astroid=2.9.0=py39haa95532_0
  - brotlipy=0.7.0=py39h2bbff1b_1003
  - ca-certificates=2023.01.10=haa95532_0
  - certifi=2022.12.7=py39haa95532_0
  - cffi=1.15.1=py39h2bbff1b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorama=0.4.6=py39haa95532_0
  - conda=23.1.0=py39haa95532_0
  - conda-package-handling=2.0.2=py39haa95532_0
  - conda-package-streaming=0.7.0=py39haa95532_0
  - cryptography=38.0.4=py39h21b164f_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - idna=3.4=py39haa95532_0
  - isort=5.9.3=pyhd3eb1b0_0
  - lazy-object-proxy=1.6.0=py39h2bbff1b_0
  - mccabe=0.6.1=py39haa95532_2
  - openssl=1.1.1t=h2bbff1b_0
  - pip=22.3.1=py39haa95532_0
  - pluggy=1.0.0=py39haa95532_1
  - pycosat=0.6.4=py39h2bbff1b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pylint=2.12.2=py39haa95532_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py39haa95532_0
  - python=3.9.5=h6244533_3
  - requests=2.28.1=py39haa95532_0
  - ruamel.yaml=0.17.21=py39h2bbff1b_0
  - ruamel.yaml.clib=0.2.6=py39h2bbff1b_1
  - setuptools=65.6.3=py39haa95532_0
  - sqlite=3.40.1=h2bbff1b_0
  - toml=0.10.2=pyhd3eb1b0_0
  - toolz=0.12.0=py39haa95532_0
  - tqdm=4.64.1=py39haa95532_0
  - urllib3=1.26.14=py39haa95532_0
  - wheel=0.38.4=py39haa95532_0
  - win_inet_pton=1.1.0=py39haa95532_0
  - wrapt=1.13.3=py39h2bbff1b_2
  - zstandard=0.19.0=py39h2bbff1b_0
  - pip:
      - absl-py==2.1.0
      - amqp==5.3.1
      - anyio==3.6.2
      - appdirs==1.4.4
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - asttokens==2.2.1
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - attrs==22.2.0
      - backcall==0.2.0
      - beautifulsoup4==4.11.2
      - billiard==4.2.1
      - bleach==6.0.0
      - blinker==1.8.2
      - celery==5.5.3
      - click==8.1.7
      - click-didyoumean==0.3.1
      - click-plugins==1.1.1.2
      - click-repl==0.3.0
      - comm==0.1.2
      - configargparse==1.7
      - contourpy==1.0.7
      - cycler==0.11.0
      - dash==2.18.2
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - debugpy==1.6.6
      - decorator==5.1.1
      - deepface==0.0.93
      - defusedxml==0.7.1
      - executing==1.2.0
      - fastjsonschema==2.16.3
      - filelock==3.9.0
      - fire==0.6.0
      - flask==3.0.3
      - flask-cors==5.0.0
      - flatbuffers==24.3.25
      - fonttools==4.38.0
      - fqdn==1.5.1
      - fsspec==2023.4.0
      - gast==0.6.0
      - gdown==5.2.0
      - google-pasta==0.2.0
      - grpcio==1.66.1
      - gunicorn==23.0.0
      - h5py==3.11.0
      - importlib-metadata==6.0.0
      - importlib-resources==5.12.0
      - ipykernel==6.21.2
      - ipython==8.10.0
      - ipython-genutils==0.2.0
      - ipywidgets==8.0.4
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jedi==0.18.2
      - jinja2==3.1.2
      - jsonpointer==2.3
      - jsonschema==4.17.3
      - jupyter==1.0.0
      - jupyter-client==8.0.3
      - jupyter-console==6.6.1
      - jupyter-core==5.2.0
      - jupyter-events==0.6.3
      - jupyter-server==2.3.0
      - jupyter-server-terminals==0.4.4
      - jupyterlab-pygments==0.2.2
      - jupyterlab-widgets==3.0.5
      - keras==3.5.0
      - kiwisolver==1.4.4
      - kombu==5.5.4
      - libclang==18.1.1
      - lmdb==1.4.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.2
      - matplotlib==3.7.0
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - mistune==2.0.5
      - ml-dtypes==0.4.0
      - mpmath==1.3.0
      - mtcnn==0.1.1
      - namex==0.0.8
      - nbclassic==0.5.2
      - nbclient==0.7.2
      - nbconvert==7.2.9
      - nbformat==5.7.3
      - nest-asyncio==1.5.6
      - networkx==3.2.1
      - notebook==6.5.2
      - notebook-shim==0.2.2
      - numpy==1.24.2
      - open3d==0.18.0
      - opencv-python==4.10.0.84
      - opt-einsum==3.3.0
      - optree==0.12.1
      - packaging==23.0
      - pandas==2.2.2
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pathtools==0.1.2
      - pickleshare==0.7.5
      - pillow==9.4.0
      - platformdirs==3.0.0
      - plotly==5.24.1
      - prometheus-client==0.16.0
      - prompt-toolkit==3.0.37
      - protobuf==4.25.4
      - psutil==5.9.4
      - pure-eval==0.2.2
      - pygments==2.14.0
      - pyparsing==3.0.9
      - pyrsistent==0.19.3
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - python-version==0.0.2
      - pytz==2023.3
      - pywinpty==2.0.10
      - pyyaml==6.0
      - pyzmq==25.0.0
      - qtconsole==5.4.0
      - qtpy==2.3.0
      - redis==6.4.0
      - retina-face==0.0.17
      - retrying==1.3.4
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.8.0
      - scipy==1.10.1
      - send2trash==1.8.0
      - six==1.16.0
      - sniffio==1.3.0
      - soupsieve==2.4
      - stack-data==0.6.2
      - sympy==1.12
      - tenacity==9.0.0
      - tensorboard==2.17.1
      - tensorboard-data-server==0.7.2
      - tensorflow-intel==2.17.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.4.0
      - terminado==0.17.1
      - tf-keras==2.17.0
      - tifffile==2023.4.12
      - tinycss2==1.2.1
      - torch==2.2.2+cu121
      - torchaudio==2.2.2+cu121
      - torchvision==0.17.2+cu121
      - tornado==6.2
      - traitlets==5.9.0
      - typing-extensions==4.8.0
      - tzdata==2025.2
      - uri-template==1.2.0
      - vine==5.1.0
      - wcwidth==0.2.6
      - webcolors==1.12
      - webencodings==0.5.1
      - websocket-client==1.5.1
      - werkzeug==3.0.4
      - widgetsnbextension==4.0.5
      - zipp==3.15.0
prefix: C:\Users\Eleven\miniconda3
